// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ReturnPath/story-points/store (interfaces: Store)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockStore is a mock of Store interface
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetBits mocks base method
func (m *MockStore) GetBits() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBits")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBits indicates an expected call of GetBits
func (mr *MockStoreMockRecorder) GetBits() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBits", reflect.TypeOf((*MockStore)(nil).GetBits))
}
