export enum Events {
  COMPLETE_STATE = 'state-of-the-state',
  PARTICIPANT_JOINED = 'participant-joined',
  PARTICIPANT_REMOVED = 'participant-removed',
  POINT_SUBMITTED = 'point-submitted',
  SESSION_CREATED = 'session-created',
  SESSION_STATE = 'session-state',
  POINTS_RESET = 'points-reset',
  POINTS_REVEALED = 'points-revealed',
  TERMINATE_SESSION = 'terminate-session',
  VOTING_SCHEME = 'voting-scheme',
  GET_SESSION_NAME = 'get-session-name',
  REBERONI = 'reberoni',
  ERROR = 'error',
}
